# Generated by Django 6.0.1 on 2026-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_created_at_task_deadline_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focussession',
            old_name='completed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='focussession',
            old_name='session_minutes',
            new_name='duration_minutes',
        ),
        migrations.RenameField(
            model_name='focussession',
            old_name='xp_reward',
            new_name='xp_earned',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='motivation_snapshot',
        ),
        migrations.AddField(
            model_name='focussession',
            name='sessions_completed',
            field=models.IntegerField(default=1),
        ),
    ]
