# Generated by Django 6.0.1 on 2026-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_completed_at_focussession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
