# Generated by Django 6.0.1 on 2026-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habit_last_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_theme',
            field=models.CharField(choices=[('studies', 'Studies'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('nutrition', 'Nutrition')], default='studies', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Streak',
        ),
    ]
