# Generated by Django 6.0.1 on 2026-02-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_habit_current_streak_habit_habit_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_theme',
            field=models.CharField(choices=[('studies', 'Studies'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('nutrition', 'Nutrition')], default='studies', max_length=50),
        ),
    ]
