# Generated by Django 6.0.1 on 2026-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_primary_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_theme',
            field=models.CharField(choices=[('studies', 'Studies'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('nutrition', 'Nutrition')], default='studies', max_length=50),
        ),
    ]
