# Generated by Django 6.0.1 on 2026-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_task_task_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_focus_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_xp',
            field=models.IntegerField(default=0),
        ),
    ]
