# Generated by Django 6.0.1 on 2026-02-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userprofile_weekly_focus_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_focus_minutes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_xp',
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='weekly_focus_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='weekly_xp',
            field=models.IntegerField(default=0),
        ),
    ]
